---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create load balancer (with workaround for issue #3444)
      ec2_elb_lb:
        name: "{{ elb_name }}"
        state: present
        region: us-east-1
        zones: 
          - us-east-1b
          - us-east-1c
          - us-east-1d
          - us-east-1e
        purge_instance_ids: true
        listeners:
          - protocol: http # options are http, https, ssl, tcp
            load_balancer_port: 80
            instance_port: 80
            proxy_protocol: True
          - protocol: http
            load_balancer_port: 8080
            instance_port: 8080
            proxy_protocol: True
        health_check:
            ping_protocol: http # options are http, https, ssl, tcp
            ping_port: 8080
            ping_path: "/index.html" # not required for tcp or ssl
            response_timeout: 5 # seconds
            interval: 30 # seconds
            unhealthy_threshold: 2
            healthy_threshold: 10
      register: elb_result
      until: "elb_result.module_stderr is not defined"
      retries: 2
      delay: 1
